behaviors:
  TechGuy:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 200
    checkpoint_interval: 500000
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
  Locksmith:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 200
    checkpoint_interval: 500000
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
environment_parameters:
  max_steps_in_fov_ls:
    curriculum:
      - name: Lesson0 # The is the start of lesson 1
        completion_criteria:
          measure: reward
          behavior: Locksmith
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 600.0
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Locksmith
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.4
        value: 500.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Locksmith
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.3
        value: 400.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Locksmith
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.2
        value: 300.0
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: Locksmith
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.1
        value: 200.0
      - name: Lesson5
        completion_criteria:
          measure: reward
          behavior: Locksmith
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 150.0
      - name: Lesson6
        value: 100.0
  max_steps_in_fov_tg:
    curriculum:
      - name: Lesson0 # The is the start of lesson 1
        completion_criteria:
          measure: reward
          behavior: TechGuy
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 600.0
      - name: Lesson1 # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: TechGuy
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.4
        value: 500.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: TechGuy
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.3
        value: 400.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: TechGuy
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.2
        value: 300.0
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: TechGuy
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.1
        value: 200.0
      - name: Lesson5
        completion_criteria:
          measure: reward
          behavior: TechGuy
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.0
        value: 150.0
      - name: Lesson6
        value: 100.0